wallpaper/backgrounds/cybint/* usr/share/backgrounds/cybint
wallpaper/backgrounds/cybint-4x3/* usr/share/backgrounds/cybint-4x3
wallpaper/backgrounds/cybint-16x9/* usr/share/backgrounds/cybint-16x9

wallpaper/wallpapers/BlueCyclone usr/share/wallpapers
wallpaper/wallpapers/FallenSky usr/share/wallpapers
wallpaper/wallpapers/GatheringStorm usr/share/wallpapers

wallpaper/gnome-background-properties/cybint-wallpapers.xml usr/share/gnome-background-properties
