// Copyright 2024 Rangertaha. All Rights Reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// The storage format of the pkg/kb dataset. It is an implementation detail of
// that package: callers work with kb.Layout, which these messages are decoded
// into. Regenerate the Go bindings with `go generate ./pkg/kb`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: kb.proto

package kbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Form is the physical shape of the alphanumeric block, which decides where
// the keys around its edges sit.
type Form int32

const (
	Form_FORM_UNSPECIFIED Form = 0
	Form_FORM_ANSI        Form = 1
	Form_FORM_ISO         Form = 2
	Form_FORM_JIS         Form = 3
)

// Enum value maps for Form.
var (
	Form_name = map[int32]string{
		0: "FORM_UNSPECIFIED",
		1: "FORM_ANSI",
		2: "FORM_ISO",
		3: "FORM_JIS",
	}
	Form_value = map[string]int32{
		"FORM_UNSPECIFIED": 0,
		"FORM_ANSI":        1,
		"FORM_ISO":         2,
		"FORM_JIS":         3,
	}
)

func (x Form) Enum() *Form {
	p := new(Form)
	*p = x
	return p
}

func (x Form) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Form) Descriptor() protoreflect.EnumDescriptor {
	return file_kb_proto_enumTypes[0].Descriptor()
}

func (Form) Type() protoreflect.EnumType {
	return &file_kb_proto_enumTypes[0]
}

func (x Form) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Form.Descriptor instead.
func (Form) EnumDescriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{0}
}

// VirtualKey is the Windows virtual key a switch maps to. The numbers are the
// codes Windows itself uses, so the enum is the real thing rather than an
// index into a list, and protoc's generated name tables convert to and from
// the "VK_Q" spelling for free.
//
// Only the keys of the alphanumeric block appear here, which is all the
// dataset stores. A layout naming any other virtual key is rejected when the
// dataset is built rather than silently recorded as unspecified.
type VirtualKey int32

const (
	VirtualKey_VK_UNSPECIFIED VirtualKey = 0
	VirtualKey_VK_TAB         VirtualKey = 9
	VirtualKey_VK_CAPITAL     VirtualKey = 20
	VirtualKey_VK_SPACE       VirtualKey = 32
	VirtualKey_VK_LSHIFT      VirtualKey = 160
	VirtualKey_VK_0           VirtualKey = 48
	VirtualKey_VK_1           VirtualKey = 49
	VirtualKey_VK_2           VirtualKey = 50
	VirtualKey_VK_3           VirtualKey = 51
	VirtualKey_VK_4           VirtualKey = 52
	VirtualKey_VK_5           VirtualKey = 53
	VirtualKey_VK_6           VirtualKey = 54
	VirtualKey_VK_7           VirtualKey = 55
	VirtualKey_VK_8           VirtualKey = 56
	VirtualKey_VK_9           VirtualKey = 57
	VirtualKey_VK_A           VirtualKey = 65
	VirtualKey_VK_B           VirtualKey = 66
	VirtualKey_VK_C           VirtualKey = 67
	VirtualKey_VK_D           VirtualKey = 68
	VirtualKey_VK_E           VirtualKey = 69
	VirtualKey_VK_F           VirtualKey = 70
	VirtualKey_VK_G           VirtualKey = 71
	VirtualKey_VK_H           VirtualKey = 72
	VirtualKey_VK_I           VirtualKey = 73
	VirtualKey_VK_J           VirtualKey = 74
	VirtualKey_VK_K           VirtualKey = 75
	VirtualKey_VK_L           VirtualKey = 76
	VirtualKey_VK_M           VirtualKey = 77
	VirtualKey_VK_N           VirtualKey = 78
	VirtualKey_VK_O           VirtualKey = 79
	VirtualKey_VK_P           VirtualKey = 80
	VirtualKey_VK_Q           VirtualKey = 81
	VirtualKey_VK_R           VirtualKey = 82
	VirtualKey_VK_S           VirtualKey = 83
	VirtualKey_VK_T           VirtualKey = 84
	VirtualKey_VK_U           VirtualKey = 85
	VirtualKey_VK_V           VirtualKey = 86
	VirtualKey_VK_W           VirtualKey = 87
	VirtualKey_VK_X           VirtualKey = 88
	VirtualKey_VK_Y           VirtualKey = 89
	VirtualKey_VK_Z           VirtualKey = 90
	// The OEM keys, whose meaning is the layout's to decide. On a US keyboard
	// VK_OEM_1 is the semicolon; elsewhere it is whatever that switch types.
	VirtualKey_VK_OEM_1      VirtualKey = 186
	VirtualKey_VK_OEM_PLUS   VirtualKey = 187
	VirtualKey_VK_OEM_COMMA  VirtualKey = 188
	VirtualKey_VK_OEM_MINUS  VirtualKey = 189
	VirtualKey_VK_OEM_PERIOD VirtualKey = 190
	VirtualKey_VK_OEM_2      VirtualKey = 191
	VirtualKey_VK_OEM_3      VirtualKey = 192
	VirtualKey_VK_OEM_4      VirtualKey = 219
	VirtualKey_VK_OEM_5      VirtualKey = 220
	VirtualKey_VK_OEM_6      VirtualKey = 221
	VirtualKey_VK_OEM_7      VirtualKey = 222
	VirtualKey_VK_OEM_8      VirtualKey = 223
	// The extra key an ISO board has and an ANSI board does not.
	VirtualKey_VK_OEM_102 VirtualKey = 226
)

// Enum value maps for VirtualKey.
var (
	VirtualKey_name = map[int32]string{
		0:   "VK_UNSPECIFIED",
		9:   "VK_TAB",
		20:  "VK_CAPITAL",
		32:  "VK_SPACE",
		160: "VK_LSHIFT",
		48:  "VK_0",
		49:  "VK_1",
		50:  "VK_2",
		51:  "VK_3",
		52:  "VK_4",
		53:  "VK_5",
		54:  "VK_6",
		55:  "VK_7",
		56:  "VK_8",
		57:  "VK_9",
		65:  "VK_A",
		66:  "VK_B",
		67:  "VK_C",
		68:  "VK_D",
		69:  "VK_E",
		70:  "VK_F",
		71:  "VK_G",
		72:  "VK_H",
		73:  "VK_I",
		74:  "VK_J",
		75:  "VK_K",
		76:  "VK_L",
		77:  "VK_M",
		78:  "VK_N",
		79:  "VK_O",
		80:  "VK_P",
		81:  "VK_Q",
		82:  "VK_R",
		83:  "VK_S",
		84:  "VK_T",
		85:  "VK_U",
		86:  "VK_V",
		87:  "VK_W",
		88:  "VK_X",
		89:  "VK_Y",
		90:  "VK_Z",
		186: "VK_OEM_1",
		187: "VK_OEM_PLUS",
		188: "VK_OEM_COMMA",
		189: "VK_OEM_MINUS",
		190: "VK_OEM_PERIOD",
		191: "VK_OEM_2",
		192: "VK_OEM_3",
		219: "VK_OEM_4",
		220: "VK_OEM_5",
		221: "VK_OEM_6",
		222: "VK_OEM_7",
		223: "VK_OEM_8",
		226: "VK_OEM_102",
	}
	VirtualKey_value = map[string]int32{
		"VK_UNSPECIFIED": 0,
		"VK_TAB":         9,
		"VK_CAPITAL":     20,
		"VK_SPACE":       32,
		"VK_LSHIFT":      160,
		"VK_0":           48,
		"VK_1":           49,
		"VK_2":           50,
		"VK_3":           51,
		"VK_4":           52,
		"VK_5":           53,
		"VK_6":           54,
		"VK_7":           55,
		"VK_8":           56,
		"VK_9":           57,
		"VK_A":           65,
		"VK_B":           66,
		"VK_C":           67,
		"VK_D":           68,
		"VK_E":           69,
		"VK_F":           70,
		"VK_G":           71,
		"VK_H":           72,
		"VK_I":           73,
		"VK_J":           74,
		"VK_K":           75,
		"VK_L":           76,
		"VK_M":           77,
		"VK_N":           78,
		"VK_O":           79,
		"VK_P":           80,
		"VK_Q":           81,
		"VK_R":           82,
		"VK_S":           83,
		"VK_T":           84,
		"VK_U":           85,
		"VK_V":           86,
		"VK_W":           87,
		"VK_X":           88,
		"VK_Y":           89,
		"VK_Z":           90,
		"VK_OEM_1":       186,
		"VK_OEM_PLUS":    187,
		"VK_OEM_COMMA":   188,
		"VK_OEM_MINUS":   189,
		"VK_OEM_PERIOD":  190,
		"VK_OEM_2":       191,
		"VK_OEM_3":       192,
		"VK_OEM_4":       219,
		"VK_OEM_5":       220,
		"VK_OEM_6":       221,
		"VK_OEM_7":       222,
		"VK_OEM_8":       223,
		"VK_OEM_102":     226,
	}
)

func (x VirtualKey) Enum() *VirtualKey {
	p := new(VirtualKey)
	*p = x
	return p
}

func (x VirtualKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VirtualKey) Descriptor() protoreflect.EnumDescriptor {
	return file_kb_proto_enumTypes[1].Descriptor()
}

func (VirtualKey) Type() protoreflect.EnumType {
	return &file_kb_proto_enumTypes[1]
}

func (x VirtualKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VirtualKey.Descriptor instead.
func (VirtualKey) EnumDescriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{1}
}

// Catalogue is the index of available layouts, kept apart from the layouts
// themselves so that listing them does not mean decoding all of them.
type Catalogue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalogue) Reset() {
	*x = Catalogue{}
	mi := &file_kb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalogue) ProtoMessage() {}

func (x *Catalogue) ProtoReflect() protoreflect.Message {
	mi := &file_kb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalogue.ProtoReflect.Descriptor instead.
func (*Catalogue) Descriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{0}
}

func (x *Catalogue) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Entry summarises a layout: enough to choose one, not enough to type on.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Form          Form                   `protobuf:"varint,3,opt,name=form,proto3,enum=urlinsane.kb.v1.Form" json:"form,omitempty"`
	Locales       []*Locale              `protobuf:"bytes,4,rep,name=locales,proto3" json:"locales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_kb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_kb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetForm() Form {
	if x != nil {
		return x.Form
	}
	return Form_FORM_UNSPECIFIED
}

func (x *Entry) GetLocales() []*Locale {
	if x != nil {
		return x.Locales
	}
	return nil
}

// Locale is one of the language identities a layout is installed under.
// Windows ships a single driver for several of them.
type Locale struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Windows keyboard layout identifier. A number, though it is always
	// shown as eight lowercase hex digits — "00000409".
	Klid uint32 `protobuf:"varint,1,opt,name=klid,proto3" json:"klid,omitempty"`
	// The BCP-47 language tag, such as "en-US".
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// How Windows names the layout for this locale.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale) Reset() {
	*x = Locale{}
	mi := &file_kb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_kb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{2}
}

func (x *Locale) GetKlid() uint32 {
	if x != nil {
		return x.Klid
	}
	return 0
}

func (x *Locale) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Locale) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Layout is a keyboard layout and everything its keys type.
type Layout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The Windows driver the layout comes from, such as "KBDUS.DLL".
	File          string    `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Form          Form      `protobuf:"varint,4,opt,name=form,proto3,enum=urlinsane.kb.v1.Form" json:"form,omitempty"`
	Locales       []*Locale `protobuf:"bytes,5,rep,name=locales,proto3" json:"locales,omitempty"`
	Keys          []*Key    `protobuf:"bytes,6,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Layout) Reset() {
	*x = Layout{}
	mi := &file_kb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_kb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{3}
}

func (x *Layout) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Layout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layout) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Layout) GetForm() Form {
	if x != nil {
		return x.Form
	}
	return Form_FORM_UNSPECIFIED
}

func (x *Layout) GetLocales() []*Locale {
	if x != nil {
		return x.Locales
	}
	return nil
}

func (x *Layout) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Key is one physical switch. Its position is not stored: it is recomputed
// from the scan code and the layout's form when the layout is loaded, so that
// the geometry lives in one place rather than being copied into every file.
type Key struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set 1 scan code. A number rather than the hex spelling the source
	// data uses: there are 10,446 keys in the dataset and the difference is
	// most of a hundred kilobytes.
	Sc uint32     `protobuf:"varint,1,opt,name=sc,proto3" json:"sc,omitempty"`
	Vk VirtualKey `protobuf:"varint,2,opt,name=vk,proto3,enum=urlinsane.kb.v1.VirtualKey" json:"vk,omitempty"`
	// The label printed on the key, when the layout gives one. Localised, so
	// it stays a string.
	Name          string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Outputs       []*Output `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_kb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_kb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{4}
}

func (x *Key) GetSc() uint32 {
	if x != nil {
		return x.Sc
	}
	return 0
}

func (x *Key) GetVk() VirtualKey {
	if x != nil {
		return x.Vk
	}
	return VirtualKey_VK_UNSPECIFIED
}

func (x *Key) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Key) GetOutputs() []*Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Output is what a key produces in one modifier state.
type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The held modifiers, as the bitmask kb.Mod uses.
	Mod uint32 `protobuf:"varint,1,opt,name=mod,proto3" json:"mod,omitempty"`
	// The character typed. Occasionally more than one rune: a few layouts have
	// ligature keys, and a dead key gives the spacing form of its accent.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Set when the key arms an accent for the next keystroke rather than
	// typing text of its own.
	Dead          bool `protobuf:"varint,3,opt,name=dead,proto3" json:"dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_kb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_kb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_kb_proto_rawDescGZIP(), []int{5}
}

func (x *Output) GetMod() uint32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

func (x *Output) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Output) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

var File_kb_proto protoreflect.FileDescriptor

const file_kb_proto_rawDesc = "" +
	"\n" +
	"\bkb.proto\x12\x0furlinsane.kb.v1\"=\n" +
	"\tCatalogue\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.urlinsane.kb.v1.EntryR\aentries\"\x89\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04form\x18\x03 \x01(\x0e2\x15.urlinsane.kb.v1.FormR\x04form\x121\n" +
	"\alocales\x18\x04 \x03(\v2\x17.urlinsane.kb.v1.LocaleR\alocales\"B\n" +
	"\x06Locale\x12\x12\n" +
	"\x04klid\x18\x01 \x01(\rR\x04klid\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xc8\x01\n" +
	"\x06Layout\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12)\n" +
	"\x04form\x18\x04 \x01(\x0e2\x15.urlinsane.kb.v1.FormR\x04form\x121\n" +
	"\alocales\x18\x05 \x03(\v2\x17.urlinsane.kb.v1.LocaleR\alocales\x12(\n" +
	"\x04keys\x18\x06 \x03(\v2\x14.urlinsane.kb.v1.KeyR\x04keys\"\x89\x01\n" +
	"\x03Key\x12\x0e\n" +
	"\x02sc\x18\x01 \x01(\rR\x02sc\x12+\n" +
	"\x02vk\x18\x02 \x01(\x0e2\x1b.urlinsane.kb.v1.VirtualKeyR\x02vk\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x121\n" +
	"\aoutputs\x18\x04 \x03(\v2\x17.urlinsane.kb.v1.OutputR\aoutputs\"B\n" +
	"\x06Output\x12\x10\n" +
	"\x03mod\x18\x01 \x01(\rR\x03mod\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04dead\x18\x03 \x01(\bR\x04dead*G\n" +
	"\x04Form\x12\x14\n" +
	"\x10FORM_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tFORM_ANSI\x10\x01\x12\f\n" +
	"\bFORM_ISO\x10\x02\x12\f\n" +
	"\bFORM_JIS\x10\x03*\x97\x05\n" +
	"\n" +
	"VirtualKey\x12\x12\n" +
	"\x0eVK_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VK_TAB\x10\t\x12\x0e\n" +
	"\n" +
	"VK_CAPITAL\x10\x14\x12\f\n" +
	"\bVK_SPACE\x10 \x12\x0e\n" +
	"\tVK_LSHIFT\x10\xa0\x01\x12\b\n" +
	"\x04VK_0\x100\x12\b\n" +
	"\x04VK_1\x101\x12\b\n" +
	"\x04VK_2\x102\x12\b\n" +
	"\x04VK_3\x103\x12\b\n" +
	"\x04VK_4\x104\x12\b\n" +
	"\x04VK_5\x105\x12\b\n" +
	"\x04VK_6\x106\x12\b\n" +
	"\x04VK_7\x107\x12\b\n" +
	"\x04VK_8\x108\x12\b\n" +
	"\x04VK_9\x109\x12\b\n" +
	"\x04VK_A\x10A\x12\b\n" +
	"\x04VK_B\x10B\x12\b\n" +
	"\x04VK_C\x10C\x12\b\n" +
	"\x04VK_D\x10D\x12\b\n" +
	"\x04VK_E\x10E\x12\b\n" +
	"\x04VK_F\x10F\x12\b\n" +
	"\x04VK_G\x10G\x12\b\n" +
	"\x04VK_H\x10H\x12\b\n" +
	"\x04VK_I\x10I\x12\b\n" +
	"\x04VK_J\x10J\x12\b\n" +
	"\x04VK_K\x10K\x12\b\n" +
	"\x04VK_L\x10L\x12\b\n" +
	"\x04VK_M\x10M\x12\b\n" +
	"\x04VK_N\x10N\x12\b\n" +
	"\x04VK_O\x10O\x12\b\n" +
	"\x04VK_P\x10P\x12\b\n" +
	"\x04VK_Q\x10Q\x12\b\n" +
	"\x04VK_R\x10R\x12\b\n" +
	"\x04VK_S\x10S\x12\b\n" +
	"\x04VK_T\x10T\x12\b\n" +
	"\x04VK_U\x10U\x12\b\n" +
	"\x04VK_V\x10V\x12\b\n" +
	"\x04VK_W\x10W\x12\b\n" +
	"\x04VK_X\x10X\x12\b\n" +
	"\x04VK_Y\x10Y\x12\b\n" +
	"\x04VK_Z\x10Z\x12\r\n" +
	"\bVK_OEM_1\x10\xba\x01\x12\x10\n" +
	"\vVK_OEM_PLUS\x10\xbb\x01\x12\x11\n" +
	"\fVK_OEM_COMMA\x10\xbc\x01\x12\x11\n" +
	"\fVK_OEM_MINUS\x10\xbd\x01\x12\x12\n" +
	"\rVK_OEM_PERIOD\x10\xbe\x01\x12\r\n" +
	"\bVK_OEM_2\x10\xbf\x01\x12\r\n" +
	"\bVK_OEM_3\x10\xc0\x01\x12\r\n" +
	"\bVK_OEM_4\x10\xdb\x01\x12\r\n" +
	"\bVK_OEM_5\x10\xdc\x01\x12\r\n" +
	"\bVK_OEM_6\x10\xdd\x01\x12\r\n" +
	"\bVK_OEM_7\x10\xde\x01\x12\r\n" +
	"\bVK_OEM_8\x10\xdf\x01\x12\x0f\n" +
	"\n" +
	"VK_OEM_102\x10\xe2\x01B6Z4github.com/rangertaha/urlinsane/pkg/kb/internal/kbpbb\x06proto3"

var (
	file_kb_proto_rawDescOnce sync.Once
	file_kb_proto_rawDescData []byte
)

func file_kb_proto_rawDescGZIP() []byte {
	file_kb_proto_rawDescOnce.Do(func() {
		file_kb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kb_proto_rawDesc), len(file_kb_proto_rawDesc)))
	})
	return file_kb_proto_rawDescData
}

var file_kb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kb_proto_goTypes = []any{
	(Form)(0),         // 0: urlinsane.kb.v1.Form
	(VirtualKey)(0),   // 1: urlinsane.kb.v1.VirtualKey
	(*Catalogue)(nil), // 2: urlinsane.kb.v1.Catalogue
	(*Entry)(nil),     // 3: urlinsane.kb.v1.Entry
	(*Locale)(nil),    // 4: urlinsane.kb.v1.Locale
	(*Layout)(nil),    // 5: urlinsane.kb.v1.Layout
	(*Key)(nil),       // 6: urlinsane.kb.v1.Key
	(*Output)(nil),    // 7: urlinsane.kb.v1.Output
}
var file_kb_proto_depIdxs = []int32{
	3, // 0: urlinsane.kb.v1.Catalogue.entries:type_name -> urlinsane.kb.v1.Entry
	0, // 1: urlinsane.kb.v1.Entry.form:type_name -> urlinsane.kb.v1.Form
	4, // 2: urlinsane.kb.v1.Entry.locales:type_name -> urlinsane.kb.v1.Locale
	0, // 3: urlinsane.kb.v1.Layout.form:type_name -> urlinsane.kb.v1.Form
	4, // 4: urlinsane.kb.v1.Layout.locales:type_name -> urlinsane.kb.v1.Locale
	6, // 5: urlinsane.kb.v1.Layout.keys:type_name -> urlinsane.kb.v1.Key
	1, // 6: urlinsane.kb.v1.Key.vk:type_name -> urlinsane.kb.v1.VirtualKey
	7, // 7: urlinsane.kb.v1.Key.outputs:type_name -> urlinsane.kb.v1.Output
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_kb_proto_init() }
func file_kb_proto_init() {
	if File_kb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kb_proto_rawDesc), len(file_kb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kb_proto_goTypes,
		DependencyIndexes: file_kb_proto_depIdxs,
		EnumInfos:         file_kb_proto_enumTypes,
		MessageInfos:      file_kb_proto_msgTypes,
	}.Build()
	File_kb_proto = out.File
	file_kb_proto_goTypes = nil
	file_kb_proto_depIdxs = nil
}
