package all

// registered plugin
import (
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/aci"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/acs"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/ai"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/ar"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/bf"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/cm"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/cns"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/co"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/com"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/cr"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/cs"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/dcr"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/di"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/hg"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/hp"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/md"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/mh"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/ons"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/pi"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/sd"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/si"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/sp"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/tld"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/tld2"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/tld3"
	_ "github.com/rangertaha/urlinsane/plugins/algorithms/vs"
)
