name: Ares

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Commit all changed files to the repository
    - name: Commit to the repo
      run: |
        if [ $((1 + $RANDOM % 10)) -gt 7 ]; then  
          git config --global user.name "rangertaha"
          git config --global user.email "rangertaha@gmail.com"
          git add .
          # Force the build to succeed, even if no files were changed
          git commit -m 'Update generated files' || true
          git push
        fi
